$lines = @(
'# ACP Manager',
'',
'[![PowerShell](https://img.shields.io/badge/PowerShell-5.1+-blue)](https://github.com/PowerShell/PowerShell)',
'[![License](https://img.shields.io/badge/License-MIT-green)](LICENSE)',
'[![ACP Registry](https://img.shields.io/badge/ACP-Registry-purple)](https://github.com/agentclientprotocol/registry)',
'',
'**ACP Manager** is a PowerShell tool that detects, installs, updates, and manages all agents compatible with the [Agent Client Protocol](https://agentclientprotocol.com) (ACP). It serves as a unified control center for your coding agent ecosystem.',
'',
'> *One command to see what you have, what is missing, what is outdated -- and install or update it.*',
'',
'---',
'',
'## Features',
'',
'| Capability | Description |',
'|---|---|',
'| **Agent Scan** | Detects 37+ ACP agents -- installed, running, version, health status |',
'| **Installation** | Installs any ACP agent from the official registry (npm, binary, uvx, cargo) |',
'| **Updates** | Updates all outdated agents with a single command |',
'| **Bridge Management** | Starts, stops, and manages opencode, kilocode, and cursor bridges |',
'| **Remote Tunnels** | Exposes bridges via DevTunnel for mobile or cloud access |',
'| **Diagnostics** | System checks, network verification, prerequisites, ports, processes |',
'',
'---',
'',
'## Installation',
'',
'### Download',
'',
'```powershell',
'# Option A: Direct download',
'Invoke-WebRequest -Uri "https://raw.githubusercontent.com/steto/acp-manager/main/acp-manager.ps1" -OutFile "acp-manager.ps1"',
'',
'# Option B: Clone the repository',
'git clone https://github.com/steto/acp-manager',
'cd acp-manager',
'```',
'',
'### First-time setup',
'',
'```powershell',
'.\acp-manager.ps1 -Action Init',
'```',
'',
'This launches an interactive setup wizard for:',
'- Bridge ports (default: opencode=8081, kilocode=8082, cursor=8083)',
'- Auto-restart on failure',
'- Mobile mode',
'- Anonymous tunnels',
'',
'### Verify',
'',
'```powershell',
'.\acp-manager.ps1                    # Interactive mode (default)',
'.\acp-manager.ps1 -Action Status     # Bridge status + detected agents',
'.\acp-manager.ps1 -Action Diag       # System diagnostics',
'.\acp-manager.ps1 -Action Scan       # Full agent scan',
'```',
'',
'---',
'',
'## Interactive Mode',
'',
'Run `.\acp-manager.ps1` with no arguments to enter the interactive menu:',
'',
'```',
'  +-----------------------------------------------+',
'  |         ACP Manager v4.2 - Interactive        |',
'  +-----------------------------------------------+',
'',
'  [1] Scan & Detection       Scan 37+ agents, agent info, registry',
'  [2] Install & Update       Install/update agents from registry',
'  [3] Bridge Management      Start, stop, restart, status, install',
'  [4] DevTunnel              Tunnel, create, list, info, delete',
'  [5] System                 Config, diag, logs, autostart, mobile',
'  [6] Help                   Show complete help',
'  [7/q] Exit',
'',
'  Select [1-7]',
'```',
'',
'Each selection opens a sub-menu. Press `0` or `b` to go back, `q` to quit.',
'',
'### Sub-menu overview',
'',
'| Menu | Options |',
'|---|---|',
'| **Scan & Detection** | Quick scan, detailed scan, agent info, registry view, force download |',
'| **Install & Update** | List registry, install agent, update all, update specific, install bridges |',
'| **Bridge Management** | Status, start, stop, restart, install, initial setup |',
'| **DevTunnel** | Tunnel + bridge, create persistent tunnel, list, info, delete |',
'| **System** | Config, diagnostics, logs, clear logs, auto-start, mobile guide, watch mode |',
'',
'---',
'',
'## Commands Reference',
'',
'All CLI commands remain available alongside interactive mode.',
'',
'### Detection',
'',
'| Action | Parameters | Description |',
'|---|---|---|',
'| `Scan` | `[-Detailed]` `[-OutputFormat Json]` | Full scan of all ACP agents |',
'| `AgentInfo` | `-AgentId <id>` | Detailed information about a specific agent |',
'| `Registry` | `[-UpdateRegistry]` | View the official ACP registry |',
'| `InstallAgent` | `-AgentId <id>` | Install an agent from the registry |',
'| `Update` | `-AgentId <id | all>` | Update agents to the latest version |',
'',
'### Bridge Management',
'',
'| Action | Parameters | Description |',
'|---|---|---|',
'| `Status` | | Current bridge status and detected agents |',
'| `Install` | `-Bridge <name | all>` | Install ACP bridges |',
'| `Start` | `-Bridge <name | all>` | Start a bridge in the background |',
'| `Stop` | `-Bridge <name | all>` | Stop a running bridge |',
'| `Restart` | `-Bridge <name | all>` | Restart a bridge |',
'| `Init` | | Guided initial configuration |',
'',
'### DevTunnel',
'',
'| Action | Parameters | Description |',
'|---|---|---|',
'| `Tunnel` | `-Bridge <name>` `[-Anonymous]` `[-TunnelId]` | Bridge with remote tunnel |',
'| `TunnelCreate` | `[-Anonymous]` | Create a persistent tunnel |',
'| `TunnelList` | | List existing tunnels |',
'| `TunnelInfo` | `[-TunnelId]` | Tunnel details |',
'| `TunnelDelete` | `-TunnelId <id>` | Delete a tunnel |',
'',
'### System',
'',
'| Action | Parameters | Description |',
'|---|---|---|',
'| `Config` | `[-Profile]` | Show configuration |',
'| `Diag` | | System diagnostics |',
'| `Logs` | `[-LogLines N]` | View logs |',
'| `LogClear` | | Clear logs |',
'| `Autostart` | `-Bridge <name>` `[-Disable]` | Windows auto-start configuration |',
'| `Mobile` | `[-Anonymous]` | Mobile integration guide |',
'| `Watch` | | Continuous monitoring (10s refresh) |',
'| `Interactive` | | Launch interactive menu |',
'| `Help` | | Show this help |',
'',
'---',
'',
'## Agent Detection',
'',
'The detection engine uses 12+ methods to find every installed ACP agent:',
'',
'```',
' 1. PATH / Binary     Get-Command for each executable',
' 2. npm global        npm list -g --depth=0 (120s cache)',
' 3. cargo             cargo install --list (120s cache)',
' 4. pip               pip list --format=json',
' 5. uvx               uv tool list',
' 6. winget            winget list (30min cache)',
' 7. choco             choco list -li',
' 8. scoop             scoop list',
' 9. dotnet            dotnet tool list -g',
'10. go                go env GOBIN + binary search',
'11. Registry          Uninstall keys (HKLM, HKCU)',
'12. KnownPaths        Recursive search in common directories',
'```',
'',
'### Scan examples',
'',
'```powershell',
'# Quick scan',
'.\acp-manager.ps1 -Action Scan',
'',
'# Full scan with health check (CPU, RAM, ports, network)',
'.\acp-manager.ps1 -Action Scan -Detailed',
'',
'# JSON output for scripting',
'.\acp-manager.ps1 -Action Scan -OutputFormat Json',
'```',
'',
'With `-Detailed`, each running agent reports:',
'- **CPU**: Processor time via Performance Counters',
'- **RAM**: Working set in MB',
'- **Ports**: TCP listening and established connections',
'- **Status**: Working (CPU active), Idle (listening), Idle (stopped)',
'- **Network**: Active TCP connections',
'- **Uptime**: Duration since process start',
'',
'---',
'',
'## Installing Agents from Registry',
'',
'Any ACP agent can be installed directly from the [official registry](https://github.com/agentclientprotocol/registry), which contains 37+ agents with full metadata including name, version, license, description, distribution methods, and dependencies.',
'',
'```powershell',
'# View all available agents',
'.\acp-manager.ps1 -Action Registry',
'',
'# Install an agent',
'.\acp-manager.ps1 -Action InstallAgent -AgentId gemini',
'```',
'',
'The installer automatically:',
'1. Looks up the agent in the ACP registry',
'2. Displays available installation methods',
'3. Selects the best method (npm > binary > uvx > cargo)',
'4. Requests confirmation',
'5. Executes the installation',
'6. Verifies the installation',
'',
'### Examples',
'',
'```powershell',
'.\acp-manager.ps1 -Action InstallAgent -AgentId gemini',
'.\acp-manager.ps1 -Action InstallAgent -AgentId claude-acp',
'.\acp-manager.ps1 -Action InstallAgent -AgentId devin',
'```',
'',
'---',
'',
'## Updating Agents',
'',
'```powershell',
'# Update all installed agents',
'.\acp-manager.ps1 -Action Update -AgentId all',
'',
'# Update a specific agent',
'.\acp-manager.ps1 -Action Update -AgentId gemini',
'```',
'',
'Version comparison determines:',
'- **current** -- local version matches registry',
'- **outdated** -- local version is behind registry',
'- **newer** -- local version is ahead of registry',
'- **unknown** -- versions are not comparable',
'',
'---',
'',
'## Bridge Management',
'',
'```powershell',
'# Install',
'.\acp-manager.ps1 -Action Install -Bridge all',
'',
'# Start',
'.\acp-manager.ps1 -Action Start -Bridge opencode -Port 9090',
'',
'# Status',
'.\acp-manager.ps1 -Action Status',
'',
'# Stop',
'.\acp-manager.ps1 -Action Stop -Bridge all',
'',
'# Restart',
'.\acp-manager.ps1 -Action Restart -Bridge opencode',
'```',
'',
'Example status output:',
'',
'```',
'Bridge         PID   Port   RAM     Status   Health   Uptime',
'------------------------------------------------------------',
'OpenCode AI    1234  8081   45.2MB  Running  TCP OK   2h 15m',
'KiloCode       -     8082   -       Stopped  -        -',
'Cursor         -     8083   -       Not inst. -        -',
'',
'DevTunnel stopped',
'',
'ACP Registry Agents:',
'Agent          Status Version    Method',
'-------------------------------------------',
'Gemini CLI     STOP   -          KnownPath',
'Cursor         STOP   2026.05.28 PATH',
'```',
'',
'---',
'',
'## DevTunnel',
'',
'Expose bridges to the internet for remote access or mobile integration:',
'',
'```powershell',
'# Tunnel + bridge (anonymous)',
'.\acp-manager.ps1 -Action Tunnel -Bridge opencode -Anonymous',
'',
'# Tunnel with persistent ID',
'.\acp-manager.ps1 -Action Tunnel -Bridge kilocode -TunnelId my-tunnel',
'',
'# Create persistent tunnel',
'.\acp-manager.ps1 -Action TunnelCreate -Anonymous',
'```',
'',
'---',
'',
'## Watch Mode',
'',
'Continuous monitoring with automatic refresh every 10 seconds:',
'',
'```powershell',
'.\acp-manager.ps1 -Action Watch',
'```',
'',
'Press `Ctrl+C` to exit.',
'',
'---',
'',
'## Configuration',
'',
'```powershell',
'# Show current configuration',
'.\acp-manager.ps1 -Action Config',
'',
'# Show a specific profile',
'.\acp-manager.ps1 -Action Config -Profile production',
'```',
'',
'Configuration file: `%USERPROFILE%\.acp-bridges\config.json`',
'',
'```json',
'{',
'  "version": "4.2",',
'  "profile": "default",',
'  "profiles": {',
'    "default": {',
'      "ports": {',
'        "opencode": 8081,',
'        "kilocode": 8082,',
'        "cursor": 8083',
'      },',
'      "tunnel_id": "",',
'      "log_path": "%TEMP%\\acp-manager.log",',
'      "log_level": "INFO",',
'      "auto_restart": false,',
'      "anonymous_tunnel": false,',
'      "mobile_mode": false',
'    }',
'  }',
'}',
'```',
'',
'---',
'',
'## Registry Cache',
'',
'The ACP registry is cached locally at `%USERPROFILE%\.acp-bridges\registry-cache.json` with a 24-hour auto-expiry. Use `-UpdateRegistry` to force a refresh:',
'',
'```powershell',
'.\acp-manager.ps1 -Action Registry -UpdateRegistry',
'```',
'',
'---',
'',
'## Logs',
'',
'```powershell',
'# Show last 50 log lines',
'.\acp-manager.ps1 -Action Logs',
'',
'# Show last 200 lines',
'.\acp-manager.ps1 -Action Logs -LogLines 200',
'',
'# Clear logs',
'.\acp-manager.ps1 -Action LogClear',
'```',
'',
'Log levels: `ERROR` (red), `WARN` (yellow), `OK` (green), `INFO` (gray, default), `DEBUG` (dark gray).',
'',
'---',
'',
'## Windows Auto-Start',
'',
'Configure a bridge to start automatically at Windows login via Task Scheduler (no administrator rights required):',
'',
'```powershell',
'# Enable auto-start for opencode',
'.\acp-manager.ps1 -Action Autostart -Bridge opencode',
'',
'# Remove auto-start',
'.\acp-manager.ps1 -Action Autostart -Disable',
'```',
'',
'---',
'',
'## Mobile Integration',
'',
'```powershell',
'.\acp-manager.ps1 -Action Mobile',
'```',
'',
'Steps:',
'1. Install an ACP client app (e.g., Agmente on iOS)',
'2. Start bridge with tunnel',
'3. Connect using the displayed remote URL',
'',
'---',
'',
'## Architecture',
'',
'```',
'acp-manager.ps1',
'  Config',
'    Multiple profiles (default, production)',
'    Configurable ports',
'    Log level',
'  Registry',
'    Download from cdn.agentclientprotocol.com',
'    24h cache with auto-expiry',
'    Forced update via -UpdateRegistry',
'  Detection Engine',
'    Get-AgentDetection (12+ methods)',
'    Get-EnhancedDetection (wrapper with add-on methods)',
'    Intelligent caching (npm 120s, cargo 120s, winget 30min)',
'    Version comparison (current/outdated/newer)',
'  Bridge Management',
'    opencode        Start/Stop/Restart/Status',
'    kilocode        Start/Stop/Restart/Status',
'    cursor          Start/Stop/Restart/Status',
'  DevTunnel',
'    Host bridge',
'    Create/List/Info/Delete',
'    Anonymous or authenticated',
'  Update Engine',
'    Multi-method (npm, cargo, pip, binary)',
'    Binary re-download',
'  UX',
'    Interactive menu mode',
'    Sub-menus with numeric navigation',
'    ANSI formatting',
'    Tab completion',
'    Write-Progress',
'    JSON output',
'```',
'',
'---',
'',
'## Complete Examples',
'',
'```powershell',
'# Interactive mode (no arguments)',
'.\acp-manager.ps1',
'',
'# Initial setup',
'.\acp-manager.ps1 -Action Init',
'',
'# Full system scan',
'.\acp-manager.ps1 -Action Scan',
'',
'# Detailed scan with health check',
'.\acp-manager.ps1 -Action Scan -Detailed',
'',
'# Agent information',
'.\acp-manager.ps1 -Action AgentInfo -AgentId gemini',
'',
'# Install an agent from registry',
'.\acp-manager.ps1 -Action InstallAgent -AgentId claude-acp',
'',
'# Install bridges',
'.\acp-manager.ps1 -Action Install -Bridge all',
'',
'# Start bridge',
'.\acp-manager.ps1 -Action Start -Bridge opencode',
'',
'# Status',
'.\acp-manager.ps1 -Action Status',
'',
'# Remote tunnel',
'.\acp-manager.ps1 -Action Tunnel -Bridge opencode -Anonymous',
'',
'# Update all agents',
'.\acp-manager.ps1 -Action Update -AgentId all',
'',
'# Diagnostics',
'.\acp-manager.ps1 -Action Diag',
'',
'# View registry',
'.\acp-manager.ps1 -Action Registry',
'',
'# View logs',
'.\acp-manager.ps1 -Action Logs -LogLines 100',
'',
'# Watch mode (live monitoring)',
'.\acp-manager.ps1 -Action Watch',
'```',
'',
'---',
'',
'## Contributing',
'',
'Contributions are welcome:',
'',
'1. **Add an agent to the registry** -- open a PR on [github.com/agentclientprotocol/registry](https://github.com/agentclientprotocol/registry)',
'2. **Improve the detection engine** -- open an issue or PR on this repository',
'3. **Report bugs** -- open an issue with diagnostics output (`-Action Diag`)',
'4. **Suggest features** -- new actions, detection methods, integrations',
'',
'The script is a single PowerShell file for easy distribution. Major sections are organized by action.',
'',
'---',
'',
'## License',
'',
'MIT License -- see [LICENSE](LICENSE) for details.',
'',
'---',
'',
'<div align="center">',
'  Part of the <a href="https://github.com/agentclientprotocol">Agent Client Protocol</a> project',
'</div>'
)

$content = $lines -join "`r`n"
$content | Out-File -FilePath README.md -Encoding UTF8 -Force
Write-Host "README.md written successfully" -ForegroundColor Green
